### PR TITLE
Update copyright and trademark notices in licensing files

### PR DESCRIPTION
**Pull request by davelab6**
Remove duplicative information from copyright notice in OFL

List all authors in AUTHORS

Add a TRADEMARKS file

### CODE REVIEW

**Comment by davelab6** [comment]
The current OFL.txt file doesn't pass the Google Fonts requirements, so I made this to unblock @rosawagner and @vv-monsalve with the onboarding there. 

cc @tiroj

**Comment by tiroj** [comment]
@davidmjones Please review and note any issues, or proceed to merge this. I note that Elsevier now appears twice in the AUTHORS.txt file.

I don’t understand the ‘TM Math’ reserved name bit, but presume that is some legacy item?

**Comment by davelab6** [comment]
Thank you @davidmjones and @tiroj :) AFAIK all RFNs need to be retained once they are added, even though the family no longer uses them itself :)

**Comment by twardoch** [comment]
RFN is part of the original license, kind of like the copyright holder, or bits of the license text. So forks or evolutions need to retain that. If a font is merged from multiple OFL fonts, then all the copyright holders and all the constituent RFNs would need to be included if fonts used RFN. 

I hadn't really thought of this before but it does make sense.

**Pull request merged**
